name: steam_scraper
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pyarrow
  - streamlit
  - requests
  - pip:
    - playwright
    - urllib3
    - charset-normalizer
    - idna
    - certifi
